### ISSUE TITLE
Enhancement request: make the character stand up

### ISSUE THREAD

**Issue by FrostShock** [shagu/ShaguMount#1]
While this is not related to mounting, it is in the same category: not being able to cast a spell because of your current circumstance.

I would like to ask for implementing this feature: When the character is sitting (for eating/drinking or otherwise) and you try to cast a spell, make the character stand up.
IMHO this is thing is too small to make a separate addon for it.

I am posting this for whoever might want to implement it in the future.

**Comment by shagu** [comment]
Implemented with https://github.com/shagu/ShaguMount/commit/e688d31e6f7792728d2e9adf5c33bc8d48f72e75

**Comment by FrostShock** [comment]
Thanks!

Now I'm using seven Shagu* addons :)

I suggest mentioning in the description that the error sound (which is quite annoying) can also be removed by using this "addon": Error Sounds Be Gone! - https://www.curseforge.com/wow/addons/project-8021
